-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema b0ugzjkogcuw0zusl2np
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b0ugzjkogcuw0zusl2np
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b0ugzjkogcuw0zusl2np` DEFAULT CHARACTER SET utf8 ;
USE `b0ugzjkogcuw0zusl2np` ;

-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`USUARIOS` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME_USUARIO` VARCHAR(70) NOT NULL,
  `NICKNAME_USUARIO` CHAR(15) NOT NULL,
  `CONTATO` CHAR(11) NOT NULL,
  `SENHA_USUARIO` CHAR(8) NOT NULL,
  `DATA_NASC_USUARIO` DATE NOT NULL,
  `CPF_USUARIO` CHAR(11) NOT NULL,
  `RECOMENDACOES_ID_RECOMENDACOES` INT NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  UNIQUE INDEX `ID_USUARIO_UNIQUE` (`ID_USUARIO` ASC) VISIBLE,
  UNIQUE INDEX `NICKNAME_USUARIO_UNIQUE` (`NICKNAME_USUARIO` ASC) VISIBLE,
  UNIQUE INDEX `CONTATO_UNIQUE` (`CONTATO` ASC) VISIBLE,
  UNIQUE INDEX `SENHA_USUARIO_UNIQUE` (`SENHA_USUARIO` ASC) VISIBLE,
  UNIQUE INDEX `CPF_USUARIO_UNIQUE` (`CPF_USUARIO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`CATEGORIA` (
  `ID_CATEGORIA` INT NOT NULL,
  `TITULO_CATEGORIA` VARCHAR(45) NOT NULL,
  `FICHAS_ID_OBRA` INT NOT NULL,
  PRIMARY KEY (`ID_CATEGORIA`),
  UNIQUE INDEX `ID_CATEGORIA_UNIQUE` (`ID_CATEGORIA` ASC) VISIBLE,
  UNIQUE INDEX `TITULO_CATEGORIA_UNIQUE` (`TITULO_CATEGORIA` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`VIDEOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`VIDEOS` (
  `ID_VIDEOS` INT NOT NULL,
  `NOME_VIDEO` VARCHAR(45) NOT NULL,
  `HASHTAG_VIDEO` VARCHAR(30) NULL,
  `DESCR_VIDEO` VARCHAR(300) NULL,
  `CAPA_VIDEO` BLOB NULL,
  `CATEGORIA_ID_CATEGORIA` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_VIDEOS`),
  INDEX `fk_VIDEOS_CATEGORIA1_idx` (`CATEGORIA_ID_CATEGORIA` ASC) VISIBLE,
  INDEX `fk_VIDEOS_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_VIDEOS_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_ID_CATEGORIA`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`CATEGORIA` (`ID_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIDEOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`FICHAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`FICHAS` (
  `ID_OBRA` INT NOT NULL,
  `NOME_OBRA` VARCHAR(45) NOT NULL,
  `DESCR_OBRA` VARCHAR(400) NOT NULL,
  `HASHTAG_OBRA` VARCHAR(30) NOT NULL,
  `NOTA_OBRA` DECIMAL(4) NOT NULL,
  `IMG_OBRA` BLOB NULL,
  `CATEGORIA_ID_CATEGORIA` INT NOT NULL,
  `ID_CATEGORIA` INT,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_OBRA`),
  UNIQUE INDEX `ID_FICHAS_UNIQUE` (`ID_OBRA` ASC) VISIBLE,
  INDEX `fk_FICHAS_CATEGORIA1_idx` (`CATEGORIA_ID_CATEGORIA` ASC) VISIBLE,
  INDEX `fk_FICHAS_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_FICHAS_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_ID_CATEGORIA`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`CATEGORIA` (`ID_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FICHAS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`RESENHAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`RESENHAS` (
  `ID_RESENHAS` INT NOT NULL,
  `TITULO_RESENHA` VARCHAR(30) NOT NULL,
  `DESCR_RESENHAl` VARCHAR(400) NOT NULL,
  `HASHTAG_RESENHA` VARCHAR(30) NOT NULL,
  `NOTA_RESENHA` DECIMAL(4) NOT NULL,
  `IMG_RESENHA` BLOB NULL,
  `CATEGORIA_ID_CATEGORIA` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_RESENHAS`),
  UNIQUE INDEX `TITULO_RESENHA_UNIQUE` (`TITULO_RESENHA` ASC) VISIBLE,
  INDEX `fk_RESENHAS_CATEGORIA1_idx` (`CATEGORIA_ID_CATEGORIA` ASC) VISIBLE,
  INDEX `fk_RESENHAS_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_RESENHAS_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_ID_CATEGORIA`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`CATEGORIA` (`ID_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESENHAS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`PLANOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`PLANOS` (
  `ID_PLANOS` INT,
  `NOME_PLANO` VARCHAR(30) NOT NULL,
  `PRAZO_PLANO` DATE NOT NULL,
  `VALOR_PLANO` DECIMAL(3,2) NOT NULL,
  `DESCR_PLANO` TEXT(400) NOT NULL,
  PRIMARY KEY (`ID_PLANOS`),
  UNIQUE INDEX `ID_PLANOS_UNIQUE` (`ID_PLANOS` ASC) VISIBLE,
  UNIQUE INDEX `NOME_PLANO_UNIQUE` (`NOME_PLANO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`ASSINATURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`ASSINATURA` (
  `ID_ASSINATURA` INT,
  `ID_PAGAMENTO` INT,
  `ID_PLANO` INT,
  `ID_CLIENTE` INT,
  `DATA_FINAL_ASSINATURA` DATE NOT NULL,
  `PLANOS_ID_PLANOS` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_ASSINATURA`),
  UNIQUE INDEX `ID_PIX_UNIQUE` (`ID_ASSINATURA` ASC) VISIBLE,
  UNIQUE INDEX `EMAIL_PIX_UNIQUE` (`ID_CLIENTE` ASC) VISIBLE,
  UNIQUE INDEX `COPIA_COLA_PIX_UNIQUE` (`ID_PLANO` ASC) VISIBLE,
  UNIQUE INDEX `CELULAR_PIX_UNIQUE` (`ID_PAGAMENTO` ASC) VISIBLE,
  INDEX `fk_ASSINATURA_PLANOS1_idx` (`PLANOS_ID_PLANOS` ASC) VISIBLE,
  INDEX `fk_ASSINATURA_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_ASSINATURA_PLANOS1`
    FOREIGN KEY (`PLANOS_ID_PLANOS`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`PLANOS` (`ID_PLANOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASSINATURA_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`GENEROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`GENEROS` (
  `ID_GENEROS` INT NOT NULL,
  `TITULO_GENERO` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID_GENEROS`),
  UNIQUE INDEX `ID_GENEROS_UNIQUE` (`ID_GENEROS` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`PAGAMENTO` (
  `ID_PAGAMENTOS` INT,
  `FORMA_PAGAMENTO` VARCHAR(40) NOT NULL,
  `DATA_PAGAMENTO` DATE NOT NULL,
  `ASSINATURA_ID_ASSINATURA` INT NOT NULL,
  PRIMARY KEY (`ID_PAGAMENTOS`),
  UNIQUE INDEX `ID_PLANO_UNIQUE` (`DATA_PAGAMENTO` ASC) VISIBLE,
  UNIQUE INDEX `ID_PIX_UNIQUE` (`FORMA_PAGAMENTO` ASC) VISIBLE,
  UNIQUE INDEX `ID_PAGAMENTOS_UNIQUE` (`ID_PAGAMENTOS` ASC) VISIBLE,
  INDEX `fk_PAGAMENTO_ASSINATURA1_idx` (`ASSINATURA_ID_ASSINATURA` ASC) VISIBLE,
  CONSTRAINT `fk_PAGAMENTO_ASSINATURA1`
    FOREIGN KEY (`ASSINATURA_ID_ASSINATURA`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`ASSINATURA` (`ID_ASSINATURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`CATEGORIA_has_GENEROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`CATEGORIA_has_GENEROS` (
  `CATEGORIA_ID_CATEGORIA` INT NOT NULL,
  `GENEROS_ID_GENEROS` INT NOT NULL,
  PRIMARY KEY (`CATEGORIA_ID_CATEGORIA`, `GENEROS_ID_GENEROS`),
  INDEX `fk_CATEGORIA_has_GENEROS_GENEROS1_idx` (`GENEROS_ID_GENEROS` ASC) VISIBLE,
  INDEX `fk_CATEGORIA_has_GENEROS_CATEGORIA1_idx` (`CATEGORIA_ID_CATEGORIA` ASC) VISIBLE,
  CONSTRAINT `fk_CATEGORIA_has_GENEROS_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_ID_CATEGORIA`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`CATEGORIA` (`ID_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORIA_has_GENEROS_GENEROS1`
    FOREIGN KEY (`GENEROS_ID_GENEROS`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`GENEROS` (`ID_GENEROS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`AVALIACAO_FICHA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`AVALIACAO_FICHA` (
  `ID_AVALIACAO` INT NOT NULL,
  `COMENTARIO_AVALIACAO` TEXT(400) NULL,
  `NOTA_AVALIACAO` DECIMAL(2,1) NULL,
  `FICHAS_ID_OBRA` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_AVALIACAO`),
  INDEX `fk_AVALIACAO_FICHA_FICHAS1_idx` (`FICHAS_ID_OBRA` ASC) VISIBLE,
  INDEX `fk_AVALIACAO_FICHA_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_AVALIACAO_FICHA_FICHAS1`
    FOREIGN KEY (`FICHAS_ID_OBRA`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`FICHAS` (`ID_OBRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AVALIACAO_FICHA_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`FAVORITO_FICHAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`FAVORITO_FICHAS` (
  `ID_FAVORITOS` INT NOT NULL,
  `FICHAS_ID_OBRA` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  `DATA_FAV` DATETIME NOT NULL,
  PRIMARY KEY (`ID_FAVORITOS`),
  UNIQUE INDEX `ID_FAVORITOS_UNIQUE` (`ID_FAVORITOS` ASC) VISIBLE,
  INDEX `fk_FAVORITO_FICHAS_FICHAS1_idx` (`FICHAS_ID_OBRA` ASC) VISIBLE,
  INDEX `fk_FAVORITO_FICHAS_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_FAVORITO_FICHAS_FICHAS1`
    FOREIGN KEY (`FICHAS_ID_OBRA`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`FICHAS` (`ID_OBRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FAVORITO_FICHAS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`RECOMENDACOES_FICHAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`RECOMENDACOES_FICHAS` (
  `ID_RECOMENDACOES` INT NOT NULL,
  `FICHAS_ID_OBRA` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_RECOMENDACOES`),
  INDEX `fk_RECOMENDACOES_FICHAS_FICHAS1_idx` (`FICHAS_ID_OBRA` ASC) VISIBLE,
  INDEX `fk_RECOMENDACOES_FICHAS_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_RECOMENDACOES_FICHAS_FICHAS1`
    FOREIGN KEY (`FICHAS_ID_OBRA`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`FICHAS` (`ID_OBRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECOMENDACOES_FICHAS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`AVALIACAO_VIDEO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`AVALIACAO_VIDEO` (
  `ID_AVALIACAO` INT NOT NULL,
  `COMENTARIO_AVALIACAO` TEXT(300) NULL,
  `NOTA_AVALIACAO` DECIMAL(2,1) NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  `VIDEOS_ID_VIDEOS` INT NOT NULL,
  PRIMARY KEY (`ID_AVALIACAO`),
  INDEX `fk_AVALIACAO_VIDEO_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  INDEX `fk_AVALIACAO_VIDEO_VIDEOS1_idx` (`VIDEOS_ID_VIDEOS` ASC) VISIBLE,
  CONSTRAINT `fk_AVALIACAO_VIDEO_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AVALIACAO_VIDEO_VIDEOS1`
    FOREIGN KEY (`VIDEOS_ID_VIDEOS`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`VIDEOS` (`ID_VIDEOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`RECOMENDACOES_VIDEOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`RECOMENDACOES_VIDEOS` (
  `ID_RECOMENDACOES_VIDEOS` INT NOT NULL,
  `ID_USUARIO` INT,
  `ID_VIDEO` INT,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  `VIDEOS_ID_VIDEOS` INT NOT NULL,
  PRIMARY KEY (`ID_RECOMENDACOES_VIDEOS`),
  UNIQUE INDEX `ID_USUARIO_UNIQUE` (`ID_USUARIO` ASC) VISIBLE,
  UNIQUE INDEX `ID_VIDEO_UNIQUE` (`ID_VIDEO` ASC) VISIBLE,
  INDEX `fk_RECOMENDACOES_VIDEOS_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  INDEX `fk_RECOMENDACOES_VIDEOS_VIDEOS1_idx` (`VIDEOS_ID_VIDEOS` ASC) VISIBLE,
  CONSTRAINT `fk_RECOMENDACOES_VIDEOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECOMENDACOES_VIDEOS_VIDEOS1`
    FOREIGN KEY (`VIDEOS_ID_VIDEOS`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`VIDEOS` (`ID_VIDEOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`FAVORITO_VIDEOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`FAVORITO_VIDEOS` (
  `ID_FAVORITO` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  `VIDEOS_ID_VIDEOS` INT NOT NULL,
  `data_fav` DATETIME NULL,
  PRIMARY KEY (`ID_FAVORITO`),
  INDEX `fk_FAVORITO_VIDEOS_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  INDEX `fk_FAVORITO_VIDEOS_VIDEOS1_idx` (`VIDEOS_ID_VIDEOS` ASC) VISIBLE,
  CONSTRAINT `fk_FAVORITO_VIDEOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FAVORITO_VIDEOS_VIDEOS1`
    FOREIGN KEY (`VIDEOS_ID_VIDEOS`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`VIDEOS` (`ID_VIDEOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`FAVORITO_RESENHA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`FAVORITO_RESENHA` (
  `ID_FAVORITOS` INT,
  `RESENHAS_ID_RESENHAS` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  `DATA_FAV` DATETIME NOT NULL,
  PRIMARY KEY (`ID_FAVORITOS`),
  UNIQUE INDEX `ID_FAVORITOS_UNIQUE` (`ID_FAVORITOS` ASC) VISIBLE,
  INDEX `fk_FAVORITO_RESENHA_RESENHAS1_idx` (`RESENHAS_ID_RESENHAS` ASC) VISIBLE,
  INDEX `fk_FAVORITO_RESENHA_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_FAVORITO_RESENHA_RESENHAS1`
    FOREIGN KEY (`RESENHAS_ID_RESENHAS`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`RESENHAS` (`ID_RESENHAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FAVORITO_RESENHA_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`AVALIACAO_RESENHA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`AVALIACAO_RESENHA` (
  `ID_AVALIACAO_RESENHA` INT NOT NULL,
  `COMENTARIO_AVALIACAO_RESENHA` TEXT NOT NULL,
  `NOTA_AVALIACAO` DECIMAL(2,1) NOT NULL,
  `RESENHAS_ID_RESENHAS` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_AVALIACAO_RESENHA`),
  INDEX `fk_AVALIACAO_RESENHA_RESENHAS1_idx` (`RESENHAS_ID_RESENHAS` ASC) VISIBLE,
  INDEX `fk_AVALIACAO_RESENHA_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_AVALIACAO_RESENHA_RESENHAS1`
    FOREIGN KEY (`RESENHAS_ID_RESENHAS`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`RESENHAS` (`ID_RESENHAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AVALIACAO_RESENHA_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b0ugzjkogcuw0zusl2np`.`RECOMENDACOES_RESENHA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b0ugzjkogcuw0zusl2np`.`RECOMENDACOES_RESENHA` (
  `ID_RECOMENDACOES_RESENHA` INT NOT NULL,
  `RESENHAS_ID_RESENHAS` INT NOT NULL,
  `USUARIOS_ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_RECOMENDACOES_RESENHA`),
  INDEX `fk_RECOMENDACOES_RESENHA_RESENHAS1_idx` (`RESENHAS_ID_RESENHAS` ASC) VISIBLE,
  INDEX `fk_RECOMENDACOES_RESENHA_USUARIOS1_idx` (`USUARIOS_ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_RECOMENDACOES_RESENHA_RESENHAS1`
    FOREIGN KEY (`RESENHAS_ID_RESENHAS`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`RESENHAS` (`ID_RESENHAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECOMENDACOES_RESENHA_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID_USUARIO`)
    REFERENCES `b0ugzjkogcuw0zusl2np`.`USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
